### ISSUE TITLE
Is it possible for params receiving multiple values (array or list)

### ISSUE THREAD

**Issue by pwwang** [nextflow-io/faq#6]
Can we do
`nextflow x.nf --a 1 --a 2`
or
`nextflow x.nf --a 1 2`
to have:
`params.a == [1, 2]` ?
Or you've already had a way to do it?

**Comment by pditommaso** [comment]
Param lists are not supported, however the best workaround is the following: 

```
nextflow foo.nf --a 1,2,3
```

Then in your script: 

```
a_list = params.a?.tokenize(',') 
```

The `?` prevents a NPE if the param is not specified.

**Comment by pwwang** [comment]
@pditommaso But for files, it's very inconvenient to use autocomplete. You have to type the full path.

**Comment by pditommaso** [comment]
True. We plan to add the support for param list in a future release https://github.com/nextflow-io/nextflow/issues/129
